import React from 'react';
import * as Icons from './Icons';

export const components: { [key: string]: JSX.Element } = {
  "ico_lightdown": <Icons.LightDown/>,
  "ico_lightup": <Icons.LightUp/>,
  "ico_minus": <Icons.Minus/>,
  "ico_mode_auto": <Icons.ModeAuto/>,
  "ico_off": <Icons.Text value="OFF"  />,
  "ico_on": <Icons.Text value="ON"  />,
  "ico_plus": <Icons.Plus />,
  "ico_timer": <Icons.Timer />,
  "ico_io": <Icons.Power />,
  "ico_number_1": <Icons.Text value="1" />,
  "ico_number_2": <Icons.Text value="2" />,
  "ico_number_3": <Icons.Text value="3" />,
  "ico_number_4": <Icons.Text value="4" />,
  "ico_number_5": <Icons.Text value="5" />,
  "ico_number_6": <Icons.Text value="6" />,
  "ico_number_7": <Icons.Text value="7" />,
  "ico_number_8": <Icons.Text value="8" />,
  "ico_number_9": <Icons.Text value="9" />,
  "ico_number_10": <Icons.Text value="10" />,
  "ico_number_11": <Icons.Text value="11" />,
  "ico_number_12": <Icons.Text value="12" />,
  "ico_tv": <Icons.Text value="TV" />,
  "ico_bs": <Icons.Text value="BS" />,
  "ico_cs": <Icons.Text value="CS" />,
  "ico_am": <Icons.Text value="AM" />,
  "ico_fm": <Icons.Text value="FM" />,
  "ico_arrow_top": <Icons.ArrowTop />,
  "ico_arrow_bottom": <Icons.ArrowBottom />,
  "ico_arrow_left": <Icons.ArrowLeft />,
  "ico_arrow_right": <Icons.ArrowRight />,
  "ico_play": <Icons.Play />,
  "ico_backward": <Icons.Rewind />,
  "ico_forward": <Icons.FF />,
  "ico_previous": <Icons.ERewind />,
  "ico_next": <Icons.EFF />,
  "ico_record": <Icons.Record />,
  "ico_stop": <Icons.Stop />,
  "ico_pause": <Icons.Pause />,
  "ico_display": <Icons.TV />,
  "ico_home": <Icons.Home />,
  "ico_option": <Icons.Option />,
  "ico_subtitle": <Icons.Subtitle />,
  "ico_color_blue": <Icons.ColorBlue />,
  "ico_color_green": <Icons.ColorGreen />,
  "ico_color_red": <Icons.ColorRed />,
  "ico_color_yellow": <Icons.ColorYellow />,
  "ico_mute": <Icons.Mute />,
  "ico_tv_guide": <Icons.Schedule />,
  "ico_input": <Icons.Input />,
  "ico_select_audio": <Icons.SelectAudio />,
  "ico_return": <Icons.Return />,
  "ico_d": <Icons.Text value="d" />,
  "ico_blast": <Icons.Blast />,
  "ico_light_all": <Icons.LightAll />,
  "ico_light_night": <Icons.LightNight />,
  "ico_light_favorite": <Icons.LightFavorite />,
  "ico_ac_dry": <Icons.Dry />,
};
